---
title: "Conos for sample 7"
author: "Evelin Aasna"
date: "8/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
devtools::install_github("hms-dbmi/conos")
library(conos)
library(Seurat)
library(ggplot2)
source("/icgc/dkfzlsdf/analysis/B210/Evelin/git-repo/seurat_utils.R")
dir_path = "/icgc/dkfzlsdf/analysis/B210/data/mf/"
suffix = "/outs/filtered_gene_bc_matrices/GRCh38/"
```

```{r}
norm = "SCT"
load(file = paste0("/icgc/dkfzlsdf/analysis/B210/Evelin/seurat_object/",norm,"_seu.RData"))
barcodes07 = colnames(seu[["RNA"]]@counts[,which(seu$sample == "07")])
seu = subset(seu, cells = barcodes07)
```



```{r}
seu = Read10X( paste0( dir_path, c("cellranger201_count_23156_6_GRCh38", 
                                      "cellranger201_count_24192-25608_4839STDY7131582_GRCh38",
                                      "cellranger201_count_24192-25608_4839STDY7131583_GRCh38"), suffix))

seu <- CreateSeuratObject( seu, min.features = 500, min.cells = 3 )

seu <- PercentageFeatureSet(seu, pattern = "^MT-", col.name = "percent.mt")
high_mt_cells = names(seu$nFeature_RNA[seu$percent.mt > 20])
seu = subset(seu, cells = high_mt_cells, invert = TRUE)
```


Either log normalization or SCTransformation
```{r message = FALSE, warning=FALSE}

if (norm == "log"){
  seu <- NormalizeData(seu, normalization.method = "LogNormalize" )
  seu <- ScaleData(seu, features = rownames(seu) )
  seu <- FindVariableFeatures(seu, selection.method = "vst", nfeatures = 2000, assay = "RNA")
  
  nPCA = 20
} 
if (norm == "SCT"){
  seu <- SCTransform(seu, verbose = FALSE, conserve.memory = TRUE )
  nPCA = 30
}

seu <- RunPCA(seu, features = VariableFeatures(seu) )
#seu <- RunUMAP(seu, dims = 1:nPCA)
seu <- RunTSNE(seu, dims = 1:nPCA )

seu <- FindNeighbors(seu, dims = 1:nPCA)
seu <- FindClusters(seu, verbose = FALSE)
seu_list = c(seu)
```


```{r}
load( file = paste0("/icgc/dkfzlsdf/analysis/B210/Evelin/decidua/",norm,"_seu_5000.RData"))
```


```{r}
seu_list[[length(seu_list)+1]] = seu
rm(seu)
```

```{r}
names(seu_list) = c("07", "decidua")

save(seu_list, file = paste0("/icgc/dkfzlsdf/analysis/B210/Evelin/seurat_object/seu_list_",norm,"_test.RData"))
```


Each sample is clustered separately
```{r message = FALSE, warning=FALSE}
# how many cores on HPC?
con <- Conos$new(seu_list, n.cores=4)

con$plotPanel(clustering="multilevel", use.local.clusters=T, title.size=6)
```

```{r}
con$buildGraph(k=30, k.self=5, space='PCA', ncomps=30, n.odgenes=2000, 
               matching.method='mNN', metric='angular', 
               score.component.variance=TRUE, verbose=TRUE)

con$findCommunities(method=leiden.community, resolution=1)
```

Clusters correspond between samples
```{r}
con$plotPanel(font.size=4)
```

```{r}
cellannot <- seu_list[["decidua"]]$annotation

# propagating labels from reference
new.label.probabilities <- con$propagateLabels(labels = cellannot, verbose=T, fixed.initial.labels=T)
```

```{r, fig.width=5, fig.height=5}
#pdf(paste0("/icgc/dkfzlsdf/analysis/B210/Evelin/plots/",norm,"_uncertainty.pdf"))
con$plotGraph(colors=(1 - apply(new.label.probabilities, 1, max)), show.legend=T, legend.title="Uncertainty", legend.pos=c(1, 0))
#dev.off()
```

```{r}
new.annot <- setNames(colnames(new.label.probabilities)[apply(new.label.probabilities,1,which.max)], rownames(new.label.probabilities))
#write.table(as.data.frame(new.annot), file = "/icgc/dkfzlsdf/analysis/B210/Evelin/new_annot_sct.txt", col.names = F, quote = F, row.names = T, append = F)
```

Clusters labelled based on reference
```{r}
#pdf(paste0("/icgc/dkfzlsdf/analysis/B210/Evelin/plots/",norm,"_conos_labelled_clusters.pdf"))
con$plotPanel(groups = new.annot)
#dev.off()
```


TODO: project annotations onto original UMAP that contains all 7 samples

```{r}
new.annot = new.annot[which(substr(names(new.annot), 1, 1) != "F")]

norm = "integrated"
load(file = paste0("/icgc/dkfzlsdf/analysis/B210/Evelin/seurat_object/",norm,"_seu.RData"))
```

